# Generated by Django 5.2.17 on 2026-09-13 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_tag_settag_cardtag'),
        ('social', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('set_like', 'Liked a set'), ('card_like', 'Liked a card'), ('set_comment', 'Commented on a set'), ('comment_reply', 'Replied to a comment'), ('follow', 'Followed you')], max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.carddefinition')),
                ('card_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cards.cardset')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.comment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='social_noti_recipie_33ad5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SetFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_followers', to='cards.cardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='social_setf_user_id_76a08d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'card_set'), name='follow_set_once')],
            },
        ),
    ]
