# Generated by Django 5.2.17 on 2026-10-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lounge", "0001_initial"),
        ("social", "0004_notification_one_unread_notification_per_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="lounge_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="lounge.post",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="lounge_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="lounge.reply",
            ),
        ),
    ]
