# Generated by Django 5.2.17 on 2026-10-10 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_lounge_blocks(apps, schema_editor):
    old = apps.get_model("lounge", "Block")
    new = apps.get_model("social", "Block")
    new.objects.bulk_create(
        [new(user_id=row.user_id, blocked_id=row.blocked_id) for row in old.objects.all()],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_report_lounge_post_report_lounge_reply'),
        ('lounge', '0002_post_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'blocked'), name='one_block'), models.CheckConstraint(condition=models.Q(('user', models.F('blocked')), _negated=True), name='no_self_block')],
            },
        ),
        migrations.RunPython(copy_lounge_blocks, migrations.RunPython.noop),
    ]
