# Generated by Django 5.2.17 on 2026-10-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_bright_colours_and_mark_badge'),
        ('lounge', '0004_social_features'),
        ('social', '0006_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='one_unread_notification_per_target',
        ),
        migrations.AddField(
            model_name='notification',
            name='lounge_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lounge.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lounge_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lounge.reply'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('set_like', 'Liked a set'), ('card_like', 'Liked a card'), ('set_comment', 'Commented on a set'), ('comment_reply', 'Replied to a comment'), ('follow', 'Followed you'), ('lounge_reply', 'Replied in the Lounge'), ('lounge_mention', 'Mentioned you in the Lounge')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('read_at__isnull', True)), fields=('recipient', 'actor', 'kind', 'card_set', 'card', 'comment', 'lounge_post', 'lounge_reply'), name='one_unread_notification_per_target', nulls_distinct=False),
        ),
    ]
