# Generated by Django 5.2.17 on 2026-10-09 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StarGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("web", "Website"), ("play", "Google Play")],
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=30)),
                (
                    "subscription_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("units", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Verified payment grant"),
                            ("spend", "Pack opening"),
                            ("reward", "Creator reward"),
                            ("closure", "Account closed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("units", models.BigIntegerField()),
                ("balance_after", models.PositiveBigIntegerField()),
                ("remainder_after", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="packs.packopening",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.stargrant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("web", "Website"), ("play", "Google Play")],
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("auto_renews", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("bonus_packs_remaining", models.PositiveSmallIntegerField(default=10)),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period",
                        to="billing.stargrant",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="billing.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StarBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.PositiveBigIntegerField(default=0)),
                ("reward_remainder", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reward_remainder__lt", 100)),
                        name="star_remainder_range",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stargrant",
            constraint=models.UniqueConstraint(
                fields=("provider", "reference"), name="one_verified_star_grant"
            ),
        ),
        migrations.AddIndex(
            model_name="starentry",
            index=models.Index(
                fields=["user", "created_at"], name="billing_sta_user_id_172988_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="starentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("opening__isnull", False)),
                fields=("user", "opening", "kind"),
                name="one_star_entry_per_opening_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="starentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("grant__isnull", False)),
                fields=("grant",),
                name="one_star_entry_per_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("provider", "reference"), name="one_subscription_account"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionperiod",
            index=models.Index(
                fields=["subscription", "starts_at", "ends_at"],
                name="billing_sub_subscri_a1b417_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="subscription_period_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("bonus_packs_remaining__lte", 10)),
                name="subscription_bonus_limit",
            ),
        ),
    ]
