# Generated by Django 5.2.17 on 2026-10-10 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_membershipsettings'),
        ('packs', '0002_packopening_points_spent_packopening_request_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='starentry',
            name='one_star_entry_per_grant',
        ),
        migrations.AlterField(
            model_name='starbalance',
            name='units',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starentry',
            name='balance_after',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='starentry',
            name='kind',
            field=models.CharField(choices=[('grant', 'Verified payment grant'), ('spend', 'Pack opening'), ('reward', 'Creator reward'), ('closure', 'Account closed'), ('refund', 'Refunded payment')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='starentry',
            constraint=models.UniqueConstraint(condition=models.Q(('grant__isnull', False), ('kind', 'grant')), fields=('grant',), name='one_star_entry_per_grant'),
        ),
    ]
