# Generated by Django 5.2.17 on 2026-10-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_refund_reversals'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingreview',
            name='provider',
            field=models.CharField(choices=[('web', 'Website'), ('play', 'Google Play')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='billingreview',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.stripeevent'),
        ),
    ]
