# Generated by Django 5.2.17 on 2026-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_play_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsettings',
            name='badge_colour',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('rose', 'Rose gold'), ('jade', 'Jade'), ('sapphire', 'Sapphire')], default='gold', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipsettings',
            name='badge_finish',
            field=models.CharField(choices=[('foil', 'Foil'), ('satin', 'Satin'), ('holo', 'Holographic')], default='foil', max_length=10),
        ),
    ]
