# Generated by Django 5.2.17 on 2026-09-02 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackOpening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("free", "Daily free pack"),
                            ("points", "Bought with set points"),
                        ],
                        max_length=10,
                    ),
                ),
                ("opened_on", models.DateField()),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_openings",
                        to="cards.cardset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_openings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnedCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="cards.carddefinition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pack_opening",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="packs.packopening",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquired_at"],
            },
        ),
        migrations.CreateModel(
            name="SetPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                (
                    "card_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="cards.cardset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="packopening",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "free")),
                fields=("user", "card_set", "opened_on"),
                name="one_free_pack_per_set_per_day",
            ),
        ),
        migrations.AddIndex(
            model_name="ownedcard",
            index=models.Index(
                fields=["owner", "card"], name="packs_owned_owner_i_113a49_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="setpoints",
            constraint=models.UniqueConstraint(
                fields=("user", "card_set"), name="one_balance_per_user_set"
            ),
        ),
    ]
