# Generated by Django 5.2.17 on 2026-10-09 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("cards", "0023_bright_colours_and_mark_badge"),
        ("packs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="packopening",
            name="points_spent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packopening",
            name="request_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packopening",
            name="stars_spent_units",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="packopening",
            name="subscription_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.subscriptionperiod",
            ),
        ),
        migrations.AlterField(
            model_name="packopening",
            name="kind",
            field=models.CharField(
                choices=[
                    ("free", "Daily free pack"),
                    ("points", "Bought with set points"),
                    ("stars", "Bought with Stars and set points"),
                    ("bonus", "Monthly bonus pack"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="packopening",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_key__isnull", False)),
                fields=("user", "request_key"),
                name="one_pack_per_payment_request",
            ),
        ),
    ]
