# Generated by Django 5.2.17 on 2026-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_packopening_points_spent_packopening_request_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packopening',
            name='kind',
            field=models.CharField(choices=[('free', 'Daily free pack'), ('points', 'Bought with set points'), ('stars', 'Bought with tickets and set points'), ('bonus', 'Monthly bonus pack')], max_length=10),
        ),
    ]
