# Generated by Django 5.2.17 on 2026-09-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_showcase_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='binder_colour',
            field=models.CharField(blank=True, choices=[('teal', 'Teal'), ('moss', 'Moss'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('indigo', 'Indigo'), ('plum', 'Plum'), ('oxblood', 'Oxblood'), ('rust', 'Rust'), ('tan', 'Tan'), ('sand', 'Sand'), ('slate', 'Slate'), ('charcoal', 'Charcoal')], max_length=20),
        ),
    ]
