# Generated by Django 5.2.17 on 2026-10-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleChallenge',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('link', 'Link'), ('username', 'Username'), ('password', 'Password'), ('delete', 'Delete')], max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
