# Generated by Django 5.2.17 on 2026-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_google_identity_and_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("white-charcoal", "White / charcoal"),
                    ("grey-forest", "Grey / forest"),
                    ("grey-plum", "Grey / plum"),
                    ("cream-teal", "Cream / teal"),
                    ("fog-forest", "Fog / forest"),
                    ("mushroom-ink", "Mushroom / ink"),
                    ("pewter-ochre", "Pewter / ochre"),
                    ("dove-aubergine", "Dove / aubergine"),
                    ("stone-navy", "Stone / navy"),
                    ("ash-olive", "Ash / olive"),
                    ("graphite-teal", "Graphite / teal"),
                    ("blue-graphite-gold", "Blue graphite / gold"),
                    ("ink-copper", "Ink / copper"),
                ],
                default="stone-navy",
                max_length=30,
            ),
        ),
    ]
