# Generated by Django 5.2.17 on 2026-10-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_theme'),
        ('packs', '0003_ticket_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='packs.ownedcard'),
        ),
    ]
