# Generated by Django 5.2.17 on 2026-09-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='kind',
            field=models.CharField(choices=[('card', 'Card art'), ('cover', 'Set cover'), ('avatar', 'Avatar'), ('pack', 'Pack artwork')], max_length=10),
        ),
    ]
