# Generated by Django 5.2.17 on 2026-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='mark',
            field=models.CharField(blank=True, choices=[('waves', 'Waves'), ('leaf', 'Leaf'), ('peaks', 'Peaks'), ('crystal', 'Crystal'), ('record', 'Record'), ('feather', 'Feather'), ('star', 'Star'), ('shell', 'Shell'), ('none', 'No mark')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_colour',
            field=models.CharField(blank=True, choices=[('mint', 'Mint'), ('ocean', 'Ocean'), ('violet', 'Violet'), ('orchid', 'Orchid'), ('ember', 'Ember'), ('gold', 'Gold'), ('moss', 'Moss'), ('ash', 'Ash')], max_length=20),
        ),
    ]
