# Generated by Django 5.2.17 on 2026-09-03 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardset_mark_cardset_pack_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='emblem_scale',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AddField(
            model_name='cardset',
            name='emblem_shape',
            field=models.CharField(blank=True, choices=[('disc', 'Disc'), ('shield', 'Shield'), ('banner', 'Banner'), ('diamond', 'Diamond'), ('hex', 'Hex'), ('none', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='emblem_style',
            field=models.CharField(blank=True, choices=[('filled', 'Filled'), ('outline', 'Outline'), ('transparent', 'Transparent')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='emblem_text',
            field=models.CharField(blank=True, choices=[('ink', 'Ink'), ('teal', 'Teal'), ('gold', 'Gold'), ('white', 'White'), ('rust', 'Rust')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='mark_scale',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(140)]),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_size',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='mark',
            field=models.CharField(blank=True, choices=[('waves', 'Waves'), ('leaf', 'Leaf'), ('peaks', 'Peaks'), ('crystal', 'Crystal'), ('record', 'Record'), ('feather', 'Feather'), ('star', 'Star'), ('shell', 'Shell'), ('bolt', 'Bolt'), ('moon', 'Moon'), ('flame', 'Flame'), ('drop', 'Drop'), ('key', 'Key'), ('bloom', 'Bloom'), ('orbit', 'Orbit'), ('arrowhead', 'Arrowhead'), ('none', 'No mark')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='pack_colour',
            field=models.CharField(blank=True, choices=[('mint', 'Mint'), ('moss', 'Moss'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('sky', 'Sky'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('orchid', 'Orchid'), ('rose', 'Rose'), ('ember', 'Ember'), ('rust', 'Rust'), ('gold', 'Gold'), ('sand', 'Sand'), ('ash', 'Ash'), ('slate', 'Slate'), ('ink', 'Ink')], max_length=20),
        ),
    ]
