# Generated by Django 5.2.17 on 2026-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardset_emblem_scale_cardset_emblem_shape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='emblem_text',
            field=models.CharField(blank=True, choices=[('ink', 'Ink'), ('charcoal', 'Charcoal'), ('slate', 'Slate'), ('teal', 'Teal'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('plum', 'Plum'), ('rose', 'Rose'), ('crimson', 'Crimson'), ('rust', 'Rust'), ('ember', 'Ember'), ('gold', 'Gold'), ('bronze', 'Bronze'), ('cream', 'Cream'), ('white', 'White')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='pack_colour',
            field=models.CharField(blank=True, choices=[('mint', 'Mint'), ('moss', 'Moss'), ('forest', 'Forest'), ('ocean', 'Ocean'), ('sky', 'Sky'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('orchid', 'Orchid'), ('rose', 'Rose'), ('crimson', 'Crimson'), ('ember', 'Ember'), ('rust', 'Rust'), ('gold', 'Gold'), ('bronze', 'Bronze'), ('sand', 'Sand'), ('cream', 'Cream'), ('white', 'White'), ('silver', 'Silver'), ('ash', 'Ash'), ('slate', 'Slate'), ('charcoal', 'Charcoal'), ('black', 'Black')], max_length=20),
        ),
    ]
