# Generated by Django 5.2.17 on 2026-09-04 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_cardset_emblem_text_alter_cardset_pack_colour'),
        ('uploads', '0002_alter_image_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='emblem_layout',
            field=models.CharField(blank=True, choices=[('seal', 'Seal'), ('stacked', 'Stacked'), ('wordmark', 'Wordmark'), ('badge', 'Badge'), ('crest', 'Crest')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploads.image'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_art_mode',
            field=models.CharField(blank=True, choices=[('emblem', 'Emblem'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_art_scale',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(130)]),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_art_x',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-45), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_art_y',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-45), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_finish',
            field=models.CharField(blank=True, choices=[('gloss', 'Gloss'), ('satin', 'Satin'), ('matte', 'Matte'), ('holo', 'Holo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='emblem_shape',
            field=models.CharField(blank=True, choices=[('disc', 'Disc'), ('shield', 'Shield'), ('banner', 'Banner'), ('diamond', 'Diamond'), ('hex', 'Hex'), ('rosette', 'Rosette'), ('tablet', 'Tablet'), ('none', 'None')], max_length=20),
        ),
    ]
