# Generated by Django 5.2.17 on 2026-09-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardset_emblem_layout_cardset_pack_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='pack_art_fit',
            field=models.CharField(blank=True, choices=[('placed', 'Placed'), ('full', 'Full')], max_length=20),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_subtitle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cardset',
            name='pack_text',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
