# Generated by Django 5.2.17, then reordered by hand so the single pack image a
# set already had is carried into the new layer stack before its columns go.

from django.db import migrations, models


def to_layers(apps, schema_editor):
    """Move each set's one pack image into pack_images as the only layer."""
    CardSet = apps.get_model("cards", "CardSet")
    for card_set in CardSet.objects.exclude(pack_art__isnull=True).iterator():
        card_set.pack_images = [
            {
                "image_id": str(card_set.pack_art_id),
                "fit": card_set.pack_art_fit or "placed",
                # A full-art pack always covered the wrapper exactly and ignored
                # its scale, so 100 is the faithful translation; the old value
                # only ever meant anything for a placed image.
                "scale": 100 if card_set.pack_art_fit == "full" else card_set.pack_art_scale,
                "x": card_set.pack_art_x,
                "y": card_set.pack_art_y,
                "rotate": 0,
                "flip_x": False,
                "flip_y": False,
                "opacity": 100,
            }
        ]
        card_set.save(update_fields=["pack_images"])


def to_single(apps, schema_editor):
    """Back out: the bottom layer becomes the set's one pack image again."""
    CardSet = apps.get_model("cards", "CardSet")
    for card_set in CardSet.objects.exclude(pack_images=[]).iterator():
        layer = (card_set.pack_images or [None])[0]
        if not layer:
            continue
        card_set.pack_art_id = layer["image_id"]
        card_set.pack_art_fit = layer.get("fit", "placed")
        card_set.pack_art_scale = layer.get("scale", 70)
        card_set.pack_art_x = layer.get("x", 0)
        card_set.pack_art_y = layer.get("y", 0)
        card_set.save(
            update_fields=[
                "pack_art",
                "pack_art_fit",
                "pack_art_scale",
                "pack_art_x",
                "pack_art_y",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0006_cardset_pack_art_fit_cardset_pack_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardset",
            name="pack_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(to_layers, to_single),
        migrations.RemoveField(model_name="cardset", name="pack_art"),
        migrations.RemoveField(model_name="cardset", name="pack_art_fit"),
        migrations.RemoveField(model_name="cardset", name="pack_art_scale"),
        migrations.RemoveField(model_name="cardset", name="pack_art_x"),
        migrations.RemoveField(model_name="cardset", name="pack_art_y"),
    ]
