# Generated by Django 5.2.17 on 2026-09-04 03:38

import cards.packlayers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_pack_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='pack_layers',
            field=models.JSONField(blank=True, default=cards.packlayers.default_stack),
        ),
    ]
