# Generated by Django 5.2.17 on 2026-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_carddefinition_printed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddefinition',
            name='set_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardset',
            name='set_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
