# Generated by Django 5.2.17 on 2026-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_carddefinition_set_total_cardset_set_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddefinition',
            name='printed_text',
            field=models.TextField(blank=True, max_length=180),
        ),
    ]
