# Generated by Django 5.2.17 on 2026-09-10 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_carddefinition_printed_text'),
        ('uploads', '0003_image_source_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='set_code_suffix',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(condition=models.Q(('set_code_suffix', ''), _negated=True), fields=('set_code', 'set_code_suffix'), name='unique_printed_set_code'),
        ),
    ]
