# Generated by Django 5.2.17 on 2026-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_cardset_set_code_suffix_alter_cardset_set_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddefinition',
            name='printed_text',
            field=models.TextField(blank=True, max_length=220),
        ),
    ]
