# Generated by Django 5.2.17 on 2026-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_alter_carddefinition_printed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddefinition',
            name='render_flat_thumbnail_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
