# Generated by Django 5.2.17 on 2026-09-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_card_flat_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='render_pack_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardset',
            name='render_pack_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
