# Generated by Django 5.2.17 on 2026-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_set_pack_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='emblem_text',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('haze', 'Haze'), ('ash', 'Ash'), ('silver', 'Silver'), ('graphite', 'Graphite'), ('slate', 'Slate'), ('steel', 'Steel'), ('charcoal', 'Charcoal'), ('ink', 'Ink'), ('bone', 'Bone'), ('cream', 'Cream'), ('butter', 'Butter'), ('linen', 'Linen'), ('sand', 'Sand'), ('straw', 'Straw'), ('ochre', 'Ochre'), ('gold', 'Gold'), ('bronze', 'Bronze'), ('shell', 'Shell'), ('peach', 'Peach'), ('apricot', 'Apricot'), ('melon', 'Melon'), ('copper', 'Copper'), ('ember', 'Ember'), ('umber', 'Umber'), ('rust', 'Rust'), ('cocoa', 'Cocoa'), ('blush', 'Blush'), ('salmon', 'Salmon'), ('coral', 'Coral'), ('red', 'Red'), ('brick', 'Brick'), ('crimson', 'Crimson'), ('garnet', 'Garnet'), ('wine', 'Wine'), ('oxblood', 'Oxblood'), ('petal', 'Petal'), ('powder', 'Powder'), ('peony', 'Peony'), ('blossom', 'Blossom'), ('magenta', 'Magenta'), ('rose', 'Rose'), ('fuchsia', 'Fuchsia'), ('mulberry', 'Mulberry'), ('plum', 'Plum'), ('lavender', 'Lavender'), ('thistle', 'Thistle'), ('lilac', 'Lilac'), ('wisteria', 'Wisteria'), ('amethyst', 'Amethyst'), ('purple', 'Purple'), ('damson', 'Damson'), ('violet', 'Violet'), ('aubergine', 'Aubergine'), ('sky', 'Sky'), ('sea', 'Sea'), ('cornflower', 'Cornflower'), ('blue', 'Blue'), ('azure', 'Azure'), ('ocean', 'Ocean'), ('indigo', 'Indigo'), ('navy', 'Navy'), ('teal', 'Teal'), ('mint', 'Mint'), ('sage', 'Sage'), ('fern', 'Fern'), ('jade', 'Jade'), ('olive', 'Olive'), ('green', 'Green'), ('forest', 'Forest'), ('moss', 'Moss'), ('pine', 'Pine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='mark',
            field=models.CharField(blank=True, choices=[('waves', 'Waves'), ('leaf', 'Leaf'), ('peaks', 'Peaks'), ('crystal', 'Crystal'), ('record', 'Record'), ('feather', 'Feather'), ('star', 'Star'), ('shell', 'Shell'), ('bolt', 'Bolt'), ('moon', 'Moon'), ('flame', 'Flame'), ('drop', 'Drop'), ('key', 'Key'), ('bloom', 'Bloom'), ('orbit', 'Orbit'), ('arrowhead', 'Arrowhead'), ('acorn', 'Acorn'), ('anchor', 'Anchor'), ('beetle', 'Beetle'), ('butterfly', 'Butterfly'), ('cactus', 'Cactus'), ('cloud', 'Cloud'), ('cog', 'Cog'), ('compass', 'Compass'), ('fern', 'Fern'), ('fish', 'Fish'), ('honeycomb', 'Honeycomb'), ('lantern', 'Lantern'), ('mushroom', 'Mushroom'), ('pine', 'Pine'), ('snowflake', 'Snowflake'), ('sprout', 'Sprout'), ('none', 'No mark')], max_length=20),
        ),
    ]
