# Generated by Django 5.2.17 on 2026-09-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_alter_cardset_emblem_text_alter_cardset_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_tags', to='cards.cardset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_tags', to='cards.tag')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('card_set', 'tag'), name='one_tag_per_set')],
            },
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tags', to='cards.carddefinition')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tags', to='cards.tag')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('card', 'tag'), name='one_tag_per_card')],
            },
        ),
    ]
