# Generated by Django 5.2.17 on 2026-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_tag_settag_cardtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='mark',
            field=models.CharField(blank=True, choices=[('waves', 'Waves'), ('leaf', 'Leaf'), ('peaks', 'Peaks'), ('crystal', 'Crystal'), ('record', 'Record'), ('feather', 'Feather'), ('star', 'Star'), ('shell', 'Shell'), ('bolt', 'Bolt'), ('moon', 'Moon'), ('flame', 'Flame'), ('drop', 'Drop'), ('key', 'Key'), ('bloom', 'Bloom'), ('orbit', 'Orbit'), ('arrowhead', 'Arrowhead'), ('acorn', 'Acorn'), ('anchor', 'Anchor'), ('beetle', 'Beetle'), ('butterfly', 'Butterfly'), ('cactus', 'Cactus'), ('cloud', 'Cloud'), ('cog', 'Cog'), ('compass', 'Compass'), ('fern', 'Fern'), ('fish', 'Fish'), ('honeycomb', 'Honeycomb'), ('lantern', 'Lantern'), ('mushroom', 'Mushroom'), ('pine', 'Pine'), ('snowflake', 'Snowflake'), ('sprout', 'Sprout'), ('coin', 'Coin'), ('stamp', 'Stamp'), ('ticket', 'Ticket'), ('bottle', 'Bottle'), ('camera', 'Camera'), ('spool', 'Spool'), ('bell', 'Bell'), ('egg', 'Egg'), ('paw', 'Paw'), ('clover', 'Clover'), ('medal', 'Medal'), ('pin', 'Pin'), ('none', 'No mark')], max_length=20),
        ),
    ]
