# Generated by Django 5.2.17 on 2026-10-09 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('show', 'Show and tell'), ('trading', 'Trading'), ('making', 'Making sets'), ('questions', 'Questions'), ('other', 'Anything else')], default='other', max_length=12),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'deleted_at', 'active_at'], name='lounge_post_topic_2a6855_idx'),
        ),
    ]
