# Generated by Django 5.2.17 on 2026-10-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0002_post_topic'),
        ('social', '0006_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
